### ISSUE TITLE
无法创建机器人因为没创建环境文件

### ISSUE THREAD

**Issue by lingyuins** [lux-QAQ/Manyana_deploy#1]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'Manyana/requirements.txt'

**Comment by lingyuins** [comment]
找到问题了
./install.sh: line 203: unzip: command not found
mv: cannot stat 'Manyana-main': No such file or directory
安装时没有安装unzip

**Comment by lux-QAQ** [comment]
嗯，我把unzip加依赖里面。
