### ISSUE TITLE
启动overflow的shell脚本未添加 -Xmx 参数

### ISSUE THREAD

**Issue by miiiiiint** [lux-QAQ/Manyana_deploy#2]
如题，在低内存的设备上通过该脚本启动overflow会造成java堆空间溢出。

**Comment by lux-QAQ** [comment]
在windows版本启动器加了，忘了在linux启动参数加上

**Comment by lux-QAQ** [comment]
修改成
`java -Xmx1024m -cp "$CLASSPATH:./content/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader`

**Comment by lux-QAQ** [comment]
-Xmx1024m的数值自己根据自己服务器的内存调整。
